name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
    - name: Set up SSH for Submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SUBMODULE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Clone Submodules
      run: git submodule update --init --recursive