name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main repository
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: false  # Don't initialize submodules here

      # Set up SSH for submodules
      - name: Set up SSH for Submodules
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SUBMODULE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Clone the submodules manually
      - name: Clone Submodules
        run: |
          git submodule update --init --recursive

      # Build your project (e.g., using npm, Gatsby, etc.)
      - name: Build the project
        run: |
          # Add your build command here
          npm install
          npm run build

      # Deploy to GitHub Pages (using gh-pages or other deployment tools)
      - name: Deploy to GitHub Pages
        run: |
          # Add your deploy commands here
          npm run deploy  # Example for a deployment command
