name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: false # Avoid fetching submodules here

    - name: Set up SSH for Submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SUBMODULE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Install OpenSSL
      run: sudo apt-get install -y openssl

    - name: Clone Submodules
      run: git submodule update --init --recursive

    - name: Debug SSH Setup
      run: |
        ssh -T git@github.com || true
        ls -la ~/.ssh
        cat ~/.ssh/known_hosts
