name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: false  # Don't initialize submodules here

      # Set up SSH for Submodules
      - name: Set up SSH for Submodules
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SUBMODULE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Clone Submodules
      - name: Clone Submodules
        run: |
          git submodule update --init --recursive

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the project
      - name: Build the project
        run: |
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npm run deploy  # Ensure 'deploy' script exists in package.json
